/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectworld.ventanas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Cambios extends javax.swing.JFrame {

    /**
     * Creates new form Cambios
     */
    public Cambios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        lblInserte = new javax.swing.JLabel();
        cboPaq = new javax.swing.JComboBox<>();
        txtDom = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        chDom = new javax.swing.JCheckBox();
        chTel = new javax.swing.JCheckBox();
        chCambio = new javax.swing.JCheckBox();
        chCorreo = new javax.swing.JCheckBox();
        btnReconexion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Enviar Cambio");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 306, 124, 41));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 89, 147, 29));

        lblInserte.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        lblInserte.setText("Inserte Su Contraseña");
        getContentPane().add(lblInserte, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 41, -1, -1));

        cboPaq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete de 10mb", "Paquete de 20mb", "Paquete de 30mb", "Paquete de 50mb" }));
        cboPaq.setEnabled(false);
        getContentPane().add(cboPaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 240, 30));

        txtDom.setEnabled(false);
        getContentPane().add(txtDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 230, -1));

        txtTel.setEnabled(false);
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 230, 30));

        txtCorreo.setEnabled(false);
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 220, 30));

        chDom.setText("Cambio de Domicilio");
        chDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chDomActionPerformed(evt);
            }
        });
        getContentPane().add(chDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 30));

        chTel.setText("Cambio de Teléfono");
        chTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTelActionPerformed(evt);
            }
        });
        getContentPane().add(chTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        chCambio.setText("Cambio de Paquete de Internet");
        chCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCambioActionPerformed(evt);
            }
        });
        getContentPane().add(chCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, -1));

        chCorreo.setText("Cambio de Correo");
        chCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(chCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, -1));

        btnReconexion.setText("Reconexión");
        btnReconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconexionActionPerformed(evt);
            }
        });
        getContentPane().add(btnReconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 180, 40));

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 73, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        try{
        if(chDom.isSelected()==true){
        //    try{
            Connection conectar=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            String query="UPDATE cliente SET domicilio='"+txtDom.getText()+"' WHERE contraseña='"+pass.getText()+"'";
            Statement st=conectar.createStatement();
            st.executeUpdate(query);
        //    JOptionPane.showMessageDialog(null, "Se ha actualizado Exitosamente :D");
        //}catch(SQLException ex){
        //    System.out.println(ex.getMessage());
        //    JOptionPane.showMessageDialog(null, "Proceso no Completado");
        }
        //}
        if(chTel.isSelected()==true){
        //    try{
            Connection conectar=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            String query="UPDATE cliente SET telefonoCliente='"+txtTel.getText()+"' WHERE contraseña='"+pass.getText()+"'";
            Statement st=conectar.createStatement();
            st.executeUpdate(query);
      //      JOptionPane.showMessageDialog(null, "Se ha actualizado Exitosamente :D");
       // }catch(SQLException ex){
         //   System.out.println(ex.getMessage());
          //  JOptionPane.showMessageDialog(null, "Proceso no Completado");
        //}
        }
        if(chCambio.isSelected()==true){
            String paq="";
            String pagar="";
            int i=cboPaq.getSelectedIndex();
            if(i==0){ paq="paq10"; pagar="600";}
            if(i==1){ paq="paq20"; pagar="750";}
            if(i==2){ paq="paq30"; pagar="875";}
            if(i==3){ paq="paq50"; pagar="999";}
      //      try{
            Connection conectar=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            String query="UPDATE cliente SET paquete='"+paq+"', Pago='"+pagar+"' WHERE contraseña='"+pass.getText()+"'";
            Statement st=conectar.createStatement();
            st.executeUpdate(query);
    //        JOptionPane.showMessageDialog(null, "Se ha actualizado Exitosamente :D");
    //    }catch(SQLException ex){
           // System.out.println(ex.getMessage());
            
           // JOptionPane.showMessageDialog(null, "Proceso no Completado");
       // }
        }
        if(chCorreo.isSelected()==true){
         //   try{
            Connection conectar=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            String query="UPDATE cliente SET correo='"+txtCorreo.getText()+"' WHERE contraseña='"+pass.getText()+"'";
            Statement st=conectar.createStatement();
            st.executeUpdate(query);
       //     JOptionPane.showMessageDialog(null, "Se ha actualizado Exitosamente :D");
        //}catch(SQLException ex){
          //  System.out.println(ex.getMessage());
         //   JOptionPane.showMessageDialog(null, "Proceso no Completado");
        //}
        }
        JOptionPane.showMessageDialog(null, "Se ha actualizado Exitosamente :D");
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
    JOptionPane.showMessageDialog(null, "Proceso no Completado");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void chDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chDomActionPerformed
        txtDom.setEnabled(true);
        if(chDom.isSelected()==false){
            txtDom.setEnabled(false);
        }
    }//GEN-LAST:event_chDomActionPerformed

    private void chTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTelActionPerformed
        txtTel.setEnabled(true);
        if(chTel.isSelected()==false){
            txtTel.setEnabled(false);
        }
    }//GEN-LAST:event_chTelActionPerformed

    private void chCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCambioActionPerformed
        cboPaq.setEnabled(true);
        if(chCambio.isSelected()==false){
            cboPaq.setEnabled(false);
        }
    }//GEN-LAST:event_chCambioActionPerformed

    private void chCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCorreoActionPerformed
       txtCorreo.setEnabled(true);
       if(chCorreo.isSelected()==false){
            txtCorreo.setEnabled(false);
        }
    }//GEN-LAST:event_chCorreoActionPerformed

    private void btnReconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconexionActionPerformed
       paquetes paq=new paquetes();
       String pago3="";
       try{
            Connection conectar1=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            Statement comando= conectar1.createStatement();
            ResultSet registro =comando.executeQuery("SELECT * FROM cliente WHERE contraseña='"+pass.getText()+"' AND estado='Desactivado'");
            if(registro.next()==true){
                String paquete=registro.getString("paquete");
                String pago1=registro.getString("Pago");
               int pago2=Integer.parseInt(pago1)+150;
               pago3=Integer.toString(pago2);
            }
            else{
                JOptionPane.showMessageDialog(null, "No existe o puede que ya este Activo el cliente");
            }
            conectar1.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "No se pudo adquirir");
        }
        try{
            Connection conectar=DriverManager.getConnection("jdbc:mysql://localhost/conectWorld","Omar","123");
            String query="UPDATE cliente SET estado='Activado', Pago='"+pago3+"' WHERE contraseña='"+pass.getText()+"' AND estado='Desactivado'";
            Statement st=conectar.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Se ha Reconectado Exitosamente :D");
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Proceso no Completado");
        }
    }//GEN-LAST:event_btnReconexionActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnReconexion;
    private javax.swing.JComboBox<String> cboPaq;
    private javax.swing.JCheckBox chCambio;
    private javax.swing.JCheckBox chCorreo;
    private javax.swing.JCheckBox chDom;
    private javax.swing.JCheckBox chTel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblInserte;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
