/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectworld.ventanas;

import java.awt.*;
import java.awt.print.*;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import javax.swing.JOptionPane;
public class Pagos extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Pagos
     */
    public Pagos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        Recibo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAP = new javax.swing.JLabel();
        lblAM = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblDol = new javax.swing.JLabel();
        lblPaq = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 600));
        setMinimumSize(new java.awt.Dimension(790, 600));

        Recibo.setBackground(new java.awt.Color(204, 153, 0));
        Recibo.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 153, 102)));
        Recibo.setForeground(new java.awt.Color(204, 255, 0));
        Recibo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("ConectWorl®");
        Recibo.add(jLabel1);
        jLabel1.setBounds(263, 32, 231, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        Recibo.add(jLabel2);
        jLabel2.setBounds(112, 114, 72, 33);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        Recibo.add(jLabel3);
        jLabel3.setBounds(50, 178, 134, 33);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");
        Recibo.add(jLabel4);
        jLabel4.setBounds(47, 229, 137, 33);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        Recibo.add(jLabel5);
        jLabel5.setBounds(124, 280, 60, 33);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono:");
        Recibo.add(jLabel6);
        jLabel6.setBounds(110, 331, 74, 33);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Domicilio:");
        Recibo.add(jLabel7);
        jLabel7.setBounds(109, 382, 75, 33);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Paquete:");
        Recibo.add(jLabel8);
        jLabel8.setBounds(115, 433, 69, 33);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setText("Total a Pagar:");
        Recibo.add(jLabel10);
        jLabel10.setBounds(223, 480, 109, 33);

        lblNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblNombre);
        lblNombre.setBounds(223, 114, 298, 33);

        lblAP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblAP);
        lblAP.setBounds(223, 178, 298, 33);

        lblAM.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblAM);
        lblAM.setBounds(223, 229, 298, 33);

        lblCorreo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblCorreo);
        lblCorreo.setBounds(223, 280, 298, 33);

        lblTel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblTel);
        lblTel.setBounds(223, 331, 298, 33);

        lblDol.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblDol);
        lblDol.setBounds(223, 382, 298, 33);

        lblPaq.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblPaq);
        lblPaq.setBounds(223, 433, 298, 33);

        lblPago.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Recibo.add(lblPago);
        lblPago.setBounds(350, 480, 298, 33);

        btnPagar.setBackground(new java.awt.Color(0, 204, 204));
        btnPagar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnPagar.setText("Pagar e Imprimir");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(0, 153, 153));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Recibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
       try {
            PrinterJob gap=PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top=gap.printDialog();
            
            if(top){
                gap.print();
                JOptionPane.showMessageDialog(null, "Pagando");
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null,"ERROR DE PROGRAMA","Error\n"+ pex, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Recibo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblAM;
    public javax.swing.JLabel lblAP;
    public javax.swing.JLabel lblCorreo;
    public javax.swing.JLabel lblDol;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPago;
    public javax.swing.JLabel lblPaq;
    public javax.swing.JLabel lblTel;
    // End of variables declaration//GEN-END:variables
@Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if(index>0){
            return NO_SUCH_PAGE; 
        }
       Graphics2D hub=(Graphics2D) graf;
       hub.translate(pagfor.getImageableX()+30,pagfor.getImageableY()+30);
       hub.scale(1.0,1.0);
       
       Recibo.printAll(graf);
       return PAGE_EXISTS;
    }
}
