/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conectworld.ventanas;
import conectworld.*;
/**
 *
 * @author Omar Ángeles Pérez
 */
public class paquetes extends javax.swing.JFrame {

    /**
     * Creates new form paquetes
     */
    public paquetes() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPaq = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbPaq10 = new javax.swing.JRadioButton();
        rbPaq20 = new javax.swing.JRadioButton();
        rbPaq30 = new javax.swing.JRadioButton();
        rbPaq50 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1190, 600));
        getContentPane().setLayout(null);

        jLabel1.setText("¡SELECCIONA TU PAQUETE!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 30, 136, 14);

        bgPaq.add(rbPaq10);
        rbPaq10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbPaq10StateChanged(evt);
            }
        });
        rbPaq10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaq10ActionPerformed(evt);
            }
        });
        getContentPane().add(rbPaq10);
        rbPaq10.setBounds(450, 170, 21, 21);

        bgPaq.add(rbPaq20);
        rbPaq20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaq20ActionPerformed(evt);
            }
        });
        getContentPane().add(rbPaq20);
        rbPaq20.setBounds(920, 160, 21, 21);

        bgPaq.add(rbPaq30);
        rbPaq30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaq30ActionPerformed(evt);
            }
        });
        getContentPane().add(rbPaq30);
        rbPaq30.setBounds(450, 410, 21, 21);

        bgPaq.add(rbPaq50);
        rbPaq50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaq50ActionPerformed(evt);
            }
        });
        getContentPane().add(rbPaq50);
        rbPaq50.setBounds(930, 420, 21, 21);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Paq10:\n10 MEGAS \nLlamadas ilimitadas\na fijos y celulares\n60 canales. \ncon todos los deportes,noticias y entretenimiento.\nIncluye todos los canales locales.\n$600 al mes.");
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 420, 220);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Paq20:\n20 MEGAS \nLlamadas ilimitadas\na fijos y celulares.\n110 canales,10 en HD. \nCon todos los deportes,noticias y entretenimiento.\nIncluye todos los canales locales.\n3,000 series y películas On Demand,\nincluye acceso a conect go e conect kids app.\n$750 al mes");
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 70, 410, 220);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Paq30:\n30 MEGAS.\nLlamadas ilimitadas\na fijos y celulares.\n170 canales, 20 en HD. \nCon todos los deportes,noticias y entretenimiento.\nIncluye todos los canales locales.\n15, 000 series y películas On Demand,\nincluye acceso a conect go e conect kids app.\n$875 al mes.");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 330, 410, 200);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Paq50:\n50 MEGAS \nLlamadas ilimitadas\na fijos y celulares.\n300 canales, 60 en HD. \nCon todos los deportes,noticias y entretenimiento.\nIncluye todos los canales locales.\n30, 000 series y películas On Demand,\nincluye acceso a conect go e conect kids app.\n$999 al mes.");
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(490, 340, 420, 190);

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 59, 23);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(993, 220, 120, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPaq30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaq30ActionPerformed
        if(rbPaq30.isSelected()){
           paquete="paq30";
           pago="875";
       }
    }//GEN-LAST:event_rbPaq30ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarse re=new registrarse();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbPaq10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbPaq10StateChanged
       if(rbPaq10.isSelected()){
           paquete="paq10";
           pago="600";
       }
    }//GEN-LAST:event_rbPaq10StateChanged

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        Conectar con=new Conectar();
        con.conexion();
        con.Insertar("cliente", nombre, apellidoP, apellidoM, telefono, domicilio, correo, contraseña, estado, paquete, pago);
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void rbPaq20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaq20ActionPerformed
        if(rbPaq20.isSelected()){
           paquete="paq20";
           pago="750";
       }
    }//GEN-LAST:event_rbPaq20ActionPerformed

    private void rbPaq50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaq50ActionPerformed
        if(rbPaq50.isSelected()){
           paquete="paq50";
           pago="999";
       }
    }//GEN-LAST:event_rbPaq50ActionPerformed

    private void rbPaq10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaq10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPaq10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paquetes().setVisible(true);
            }
        });
    }
public String nombre;
public String apellidoP;
public String apellidoM;
public String telefono;
public String domicilio;
public String correo;
public String contraseña;
public String estado;
public String paquete;
public String pago;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPaq;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JRadioButton rbPaq10;
    private javax.swing.JRadioButton rbPaq20;
    private javax.swing.JRadioButton rbPaq30;
    private javax.swing.JRadioButton rbPaq50;
    // End of variables declaration//GEN-END:variables
}
